version: '3.4'

services:
  walletapp:    
    container_name: walletapp
    build: .
      # context: .
      # dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/www
    networks:
      - rede
    extra_hosts:
      - "host.docker.internal:host-gateway"
  web-walletapp:
    image: nginx:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./:/www/
    depends_on:
      - walletapp
    networks:
      - rede
    links:
      - walletapp
networks:
  rede:
    driver: bridge