
services:
  walletapp:    
    container_name: walletapp
    build: .
      # context: .
      # dockerfile: ./Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/www
    networks:
      - rede
    extra_hosts:
      - "host.docker.internal:host-gateway"
  web-walletapp:
    image: nginx:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./.docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
      - ./:/www/
    depends_on:
      - walletapp
    networks:
      - rede
    links:
      - walletapp
  walletapp-db:
    container_name: walletapp-db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: will
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_DATABASE: walletapp
      MYSQL_USER: will
      MYSQL_PASSWORD: will
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - rede
networks:
  rede:
    driver: bridge